# Generated by Django 2.1.6 on 2019-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_mission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReseachActivity',
            new_name='ResearchActivity',
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
