# Generated by Django 2.1.6 on 2019-03-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190318_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchactivity',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
