# Generated by Django 2.1.7 on 2019-03-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190318_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcooperation',
            name='content',
            field=models.CharField(max_length=1023),
        ),
    ]
