# Generated by Django 2.1.7 on 2019-03-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190322_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='content',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='member',
            name='research_interest',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='mission',
            name='content',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='content',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='researchactivity',
            name='description',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='researchactivity',
            name='name',
            field=models.CharField(max_length=1023),
        ),
    ]
