# Generated by Django 2.1.7 on 2019-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_projectobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='google_scholar_link',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin_link',
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='researchgate_link',
            field=models.CharField(max_length=511, null=True),
        ),
    ]
