# Generated by Django 2.1.7 on 2019-08-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190804_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='curriculum_vitae_link',
            field=models.CharField(max_length=511, null=True),
        ),
    ]
